services:
  - type: web
    name: pucetec-titulacion
    runtime: python
    buildCommand: bash build.sh
    startCommand: gunicorn config.wsgi:application
    disk:
      name: pucetec-media
      mountPath: /var/data
      sizeGB: 1
    envVars:
      - key: PYTHON_VERSION
        value: 3.14.6
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: MEDIA_ROOT
        value: /var/data/media
      - key: MEDIA_URL
        value: /media/
      - key: ALLOWED_HOSTS
        value: "*"