# Generated by Django 5.2.16 on 2026-07-12 04:17

import django.db.models.deletion
import documentos.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estudiantes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Acta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_acta', models.CharField(blank=True, max_length=30, unique=True, verbose_name='Número de acta')),
                ('tipo_acta', models.CharField(choices=[('TRABAJO_ESCRITO', 'Acta de titulación por trabajo escrito'), ('EXAMEN_COMPLEXIVO', 'Acta de titulación por examen complexivo')], max_length=30, verbose_name='Tipo de acta')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('GENERADA', 'Generada'), ('REVISION', 'En revisión'), ('APROBADA', 'Aprobada'), ('ANULADA', 'Anulada')], default='BORRADOR', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('archivo_word', models.FileField(blank=True, upload_to=documentos.models.ruta_acta_word)),
                ('archivo_pdf', models.FileField(blank=True, upload_to=documentos.models.ruta_acta_pdf)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_generacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actas_creadas', to=settings.AUTH_USER_MODEL)),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actas', to='estudiantes.registrotitulacion', verbose_name='Estudiante')),
            ],
            options={
                'verbose_name': 'Acta',
                'verbose_name_plural': 'Actas',
                'ordering': ['-fecha_actualizacion'],
                'constraints': [models.UniqueConstraint(fields=('registro', 'tipo_acta'), name='acta_unica_por_estudiante_y_tipo')],
            },
        ),
    ]
