# Generated by Django 5.2.16 on 2026-07-12 04:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroTitulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_banner', models.CharField(blank=True, db_index=True, max_length=30, verbose_name='ID_BANNER')),
                ('nombres_completos', models.CharField(max_length=200, verbose_name='NOMBRES COMPLETOS')),
                ('cedula', models.CharField(max_length=10, unique=True, verbose_name='CEDULA')),
                ('celular', models.CharField(blank=True, max_length=20, verbose_name='CELULAR')),
                ('correo_personal', models.EmailField(blank=True, max_length=254, verbose_name='CORREO_PERSONAL')),
                ('correo_instituc', models.EmailField(blank=True, max_length=254, verbose_name='CORREO_INSTITUC')),
                ('sede', models.CharField(blank=True, max_length=100, verbose_name='SEDE')),
                ('programa', models.CharField(max_length=150, verbose_name='PROGRAMA')),
                ('programa_desc', models.CharField(blank=True, max_length=250, verbose_name='PROGAMA_DESC')),
                ('numero_cohorte', models.CharField(blank=True, max_length=50, verbose_name='NÚMERO DE COHORTE')),
                ('periodo_ingreso', models.CharField(blank=True, max_length=100, verbose_name='PERIODO DE INGRESO')),
                ('nivel2', models.CharField(blank=True, max_length=50, verbose_name='NIVEL2')),
                ('modalidad_titulacion', models.CharField(blank=True, choices=[('TRABAJO_ESCRITO', 'Trabajo escrito'), ('EXAMEN_COMPLEXIVO', 'Examen complexivo')], max_length=30, verbose_name='MODALIDAD DE TITULACIÓN')),
                ('matricula_uic', models.CharField(blank=True, max_length=100, verbose_name='MATRICULA UIC')),
                ('periodo_titulacion_senescyt', models.CharField(blank=True, max_length=100, verbose_name='PERIODO DE TITULACIÓN SENESCYT')),
                ('estado', models.CharField(blank=True, choices=[('REGISTRADO', 'Registrado'), ('EN_PROCESO', 'En proceso'), ('REVISION', 'En revisión'), ('DEFENSA', 'Defensa'), ('APROBADO', 'Aprobado'), ('GRADUADO', 'Graduado'), ('OBSERVADO', 'Observado')], max_length=30, verbose_name='ESTADO')),
                ('cumplimiento_idioma', models.CharField(blank=True, choices=[('SI', 'Sí'), ('NO', 'No'), ('PENDIENTE', 'Pendiente')], max_length=20, verbose_name='CUMPLIMIENTO DE IDIOMA')),
                ('materia_practicas_pre_profesionales', models.CharField(blank=True, max_length=200, verbose_name='MATERIA PRÁCTICAS PRE PROFESIONALES')),
                ('horas_240', models.PositiveIntegerField(blank=True, default=240, null=True, verbose_name='HORAS 240')),
                ('materia_servicio_comunitario', models.CharField(blank=True, max_length=200, verbose_name='MATERIA SERVICIO COMUNITARIO')),
                ('horas_120', models.PositiveIntegerField(blank=True, default=120, null=True, verbose_name='HORAS 120')),
                ('nombres_completos_tutor', models.CharField(blank=True, max_length=200, verbose_name='NOMBRES COMPLETOS TUTOR')),
                ('id_tutor', models.CharField(blank=True, max_length=30, verbose_name='ID TUTOR')),
                ('tema', models.TextField(blank=True, verbose_name='TEMA')),
                ('primer_miembro_tribunal', models.CharField(blank=True, max_length=200, verbose_name='1er MIEMBRO DE TRIBUNAL - APELLIDOS Y NOMBRES COMPLETOS')),
                ('primer_miembro_id_docente', models.CharField(blank=True, max_length=30, verbose_name='1er MIEMBRO DE TRIBUNAL - ID DOCENTE')),
                ('segundo_miembro_tribunal', models.CharField(blank=True, max_length=200, verbose_name='2do MIEMBRO DE TRIBUNAL - APELLIDOS Y NOMBRES COMPLETOS')),
                ('segundo_miembro_id_docente', models.CharField(blank=True, max_length=30, verbose_name='2do MIEMBRO DE TRIBUNAL - ID DOCENTE')),
                ('tercer_miembro_tribunal', models.CharField(blank=True, max_length=200, verbose_name='3ter MIEMBRO DE TRIBUNAL - NOMBRES COMPLETOS')),
                ('tercer_miembro_id_docente', models.CharField(blank=True, max_length=30, verbose_name='3ter MIEMBRO DE TRIBUNAL - ID DOCENTE')),
                ('cuarto_miembro_tribunal', models.CharField(blank=True, max_length=200, verbose_name='4to MIEMBRO DE TRIBUNAL')),
                ('cuarto_miembro_id_docente', models.CharField(blank=True, max_length=30, verbose_name='4to MIEMBRO DE TRIBUNAL - ID DOCENTE')),
                ('proyecto_escrito', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='PROYECTO ESCRITO')),
                ('defensa_oral', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='DEFENSA ORAL')),
                ('nota_final', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='NOTA FINAL')),
                ('examen_teorico_complexivo', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='EXAMEN TEÓRICO COMPLEXIVO')),
                ('examen_teorico_practico', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='EXAMEN TEÓRICO PRÁCTICO')),
                ('nota_final2', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='NOTA FINAL2')),
                ('observacion_puce_tec', models.TextField(blank=True, verbose_name='OBSERVACIÓN PUCE TEC')),
                ('observaciones_secretaria_general', models.TextField(blank=True, verbose_name='OBSERVACIONES DE SECRETARÍA GENERAL')),
                ('nueva_observacion_puce_tec', models.TextField(blank=True, verbose_name='NUEVA OBSERVACIÓN PUCE TEC')),
                ('estado_envio_registro', models.CharField(blank=True, choices=[('NO_ENVIADO', 'No enviado'), ('ENVIADO', 'Enviado'), ('OBSERVADO', 'Observado'), ('APROBADO', 'Aprobado')], max_length=30, verbose_name='ESTADO DE ENVÍO DE REGISTRO')),
                ('fecha_grado', models.DateField(blank=True, null=True, verbose_name='Fecha de Grado')),
                ('observacion_secretaria', models.TextField(blank=True, verbose_name='Observación Secretaría')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Registro de titulación',
                'verbose_name_plural': 'Registros de titulación',
                'ordering': ['-fecha_actualizacion'],
            },
        ),
    ]
