# Generated by Django 5.2.16 on 2026-08-28 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0002_programa_historial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrotitulacion',
            name='fecha_grado',
            field=models.DateField(blank=True, null=True, verbose_name='FECHA DE GRADO'),
        ),
        migrations.AlterField(
            model_name='registrotitulacion',
            name='observacion_secretaria',
            field=models.TextField(blank=True, verbose_name='OBSERVACIÓN SECRETARÍA'),
        ),
        migrations.AlterField(
            model_name='registrotitulacion',
            name='tercer_miembro_id_docente',
            field=models.CharField(blank=True, max_length=30, verbose_name='3er MIEMBRO DE TRIBUNAL - ID DOCENTE'),
        ),
        migrations.AlterField(
            model_name='registrotitulacion',
            name='tercer_miembro_tribunal',
            field=models.CharField(blank=True, max_length=200, verbose_name='3er MIEMBRO DE TRIBUNAL - NOMBRES COMPLETOS'),
        ),
    ]
