# Generated by Django 5.2.16 on 2026-09-01 16:16

import django.db.models.deletion
from django.db import migrations, models


def respaldar_identidad_estudiante(apps, schema_editor):
    HistorialExpediente = apps.get_model(
        "estudiantes",
        "HistorialExpediente",
    )
    for cambio in HistorialExpediente.objects.select_related("registro"):
        if cambio.registro_id:
            cambio.registro_nombre = cambio.registro.nombres_completos
            cambio.registro_cedula = cambio.registro.cedula
            cambio.save(update_fields=["registro_nombre", "registro_cedula"])


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0004_programas_base_idempotentes'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialexpediente',
            name='registro_cedula',
            field=models.CharField(blank=True, db_index=True, max_length=30),
        ),
        migrations.AddField(
            model_name='historialexpediente',
            name='registro_nombre',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='historialexpediente',
            name='registro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_cambios', to='estudiantes.registrotitulacion'),
        ),
        migrations.RunPython(
            respaldar_identidad_estudiante,
            migrations.RunPython.noop,
        ),
    ]
